controllers/CancionesController.php
<?php

namespace app\controllers;

use app\models\Canciones;
use app\models\Generos;  // Importamos el modelo generos
use app\models\Instrumentos; // Importamos el modelo Instrumentos
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Yii;

class CancionesController extends Controller
{
    public function behaviors()
    {
//        return array_merge( SE COMENTA ESTE RETURN PARA UTILIZAR LA geSTION DE USUARIOS DEL USER MANAGEMENT
//            parent::behaviors(),
//            [
//                'verbs' => [
//                    'class' => VerbFilter::className(),
//                    'actions' => [
//                        'delete' => ['POST'],
//                    ],
//                ],
//            ]
//        );
        return [
		'ghost-access'=> [
			'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
		],
	];
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Canciones::find(),
        ]);

        $instrumentos = Instrumentos::find()->all(); // Obtenemos todos los instrumentos

    return $this->render('index', [
        'dataProvider' => $dataProvider,
        'instrumentos' => $instrumentos, // Pasamos la lista de instrumentos a la vista
    ]);
    }

    public function actionView($idcancion)
{
    $model = $this->findModel($idcancion); // Obtenemos el modelo Canciones correspondiente al ID
    $instrumentos = Instrumentos::find()->all(); // Obtenemos todos los instrumentos

    return $this->render('view', [
        'model' => $model, // Pasamos el modelo Canciones a la vista
        'instrumentos' => $instrumentos, // Pasamos la lista de instrumentos a la vista
    ]);
}

    public function actionCreate()    
    {
        Yii::warning('action create');
        $model = new Canciones();
        $generos = Generos::getGenerosList();

        if ($model->load(Yii::$app->request->post())) {
            $model->selectedGeneros = Yii::$app->request->post('Canciones')['selectedGeneros'];
            $model['idusuario'] = Yii::$app->user->id;
            Yii::warning('load' . $model['idusuario']);
            
            // Al crear una cancion redirige a la vista create del controla de instrumentoa 
            // y le pasa como parametro el idcancion
            if ($model->save()) {
                Yii::warning('save');
                return $this->redirect(['instrumentos/create', 'idcancion' => $model->idcancion]);
            }
            
        }

        return $this->render('create', [
            'model' => $model,
            'generos' => $generos,
        ]);
    }
//    public function actionCreate()
//    {
//        Yii::warning('action create');
//        $model = new Canciones();
//        $generos = Generos::getGenerosList();
//        $instrumentos = Instrumentos::find()->where(['idusuario' => Yii::$app->user->id])->all();
//
//        if ($model->load(Yii::$app->request->post())) {
//            $model->selectedGeneros = Yii::$app->request->post('Canciones')['selectedGeneros'];
//            $model->idusuario = Yii::$app->user->id;
//
//            if ($model->save()) {
//                // Relacionar los instrumentos seleccionados con la canción
//                $selectedInstrumentos = Yii::$app->request->post('selectedInstrumentos', []);
//                foreach ($selectedInstrumentos as $idInstrumento) {
//                    $cancionInstrumento = new \app\models\CancionInstrumento();
//                    $cancionInstrumento->idcancion = $model->idcancion;
//                    $cancionInstrumento->idinstrumento = $idInstrumento;
//                    $cancionInstrumento->save();
//                }
//
//                return $this->redirect(['view', 'idcancion' => $model->idcancion]);
//            }
//        }
//
//        return $this->render('create', [
//            'model' => $model,
//            'generos' => $generos,
//            'instrumentos' => $instrumentos,
//        ]);
//    }

    public function actionUpdate($idcancion)
    {
        $model = $this->findModel($idcancion);
        $generos = Generos::getGenerosList();

        if ($model->load(Yii::$app->request->post())) {
            $model->selectedGeneros = Yii::$app->request->post('Canciones')['selectedGeneros'];
            if ($model->save()) {
                return $this->redirect(['view', 'idcancion' => $model->idcancion]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'generos' => $generos,
        ]);
    }

    public function actionDelete($idcancion)
    {
        $this->findModel($idcancion)->delete();
        return $this->redirect(['index']);
    }

    protected function findModel($idcancion)
    {
        if (($model = Canciones::findOne(['idcancion' => $idcancion])) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('La página solicitada no existe.');
    }
    
    public static function showUserName( $userId ) {
        
        return $userId;
    }
    
}

controllers/EstudiosController.php
<?php

namespace app\controllers;

use app\models\Estudios;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Yii;

/**
 * EstudiosController implements the CRUD actions for Estudios model.
 */
class EstudiosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return [
            'ghost-access'=> [
                'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
            ],
        ];
    }

    /**
     * Lists all Estudios models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Estudios::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Estudios model.
     * @param int $idestudio Idestudio
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($idestudio)
    {
        return $this->render('view', [
            'model' => $this->findModel($idestudio),
        ]);
    }

    /**
     * Creates a new Estudios model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
{
    $model = new Estudios();

    if (Yii::$app->request->isPost) {
        if ($model->load(Yii::$app->request->post())) {
            $idcancion = Yii::$app->request->post('idcancion');
            $model->idcancion = $idcancion;

            if ($model->save()) {
                return $this->redirect( ['herramientas/create', 'idestudio' => $model->idestudio ] );
            } else {
                Yii::error('Failed to save model: ' . print_r($model->errors, true));
            }
        } else {
            Yii::error('Failed to load data into model');
        }
    } else {
        Yii::info('Request is NOT POST');
        $model->loadDefaultValues();
    }

    return $this->render('create', [
        'model' => $model,
    ]);
}

    /**
     * Updates an existing Estudios model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $idestudio Idestudio
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($idestudio)
    {
        $model = $this->findModel($idestudio);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'idestudio' => $model->idestudio]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Estudios model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $idestudio Idestudio
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($idestudio)
    {
        $this->findModel($idestudio)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Estudios model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $idestudio Idestudio
     * @return Estudios the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($idestudio)
    {
        if (($model = Estudios::findOne(['idestudio' => $idestudio])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/GenerosController.php
<?php



namespace app\controllers;

use app\models\Generos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Yii;

/**
 * GenerosController implementa las acciones CRUD para el modelo Generos.
 */
class GenerosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
//        return array_merge( SE COMENTA ESTE RETURN PARA UTILIZAR LA geSTION DE USUARIOS DEL USER MANAGEMENT
//            parent::behaviors(),
//            [
//                'verbs' => [
//                    'class' => VerbFilter::className(),
//                    'actions' => [
//                        'delete' => ['POST'],
//                    ],
//                ],
//            ]
//        );
        return [
		'ghost-access'=> [
			'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
		],
	]; 
    }

    /**
     * Lista todos los modelos de Generos.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Generos::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Muestra un solo modelo de Generos.
     * @param int $idgenero Idgenero
     * @return string
     * @throws NotFoundHttpException si no se puede encontrar el modelo
     */
    public function actionView($idgenero)
    {
        return $this->render('view', [
            'model' => $this->findModel($idgenero),
        ]);
    }

    /**
     * Crea un nuevo modelo de Generos.
     * Si la creación es exitosa, el navegador será redirigido a la página 'view'.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Generos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'idgenero' => $model->idgenero]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Actualiza un modelo existente de Generos.
     * Si la actualización es exitosa, el navegador será redirigido a la página 'view'.
     * @param int $idgenero Idgenero
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException si no se puede encontrar el modelo
     */
    public function actionUpdate($idgenero)
    {
        $model = $this->findModel($idgenero);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'idgenero' => $model->idgenero]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Elimina un modelo existente de Generos.
     * Si la eliminación es exitosa, el navegador será redirigido a la página 'index'.
     * @param int $idgenero Idgenero
     * @return \yii\web\Response
     * @throws NotFoundHttpException si no se puede encontrar el modelo
     */
    public function actionDelete($idgenero)
    {
        $this->findModel($idgenero)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Encuentra el modelo de Generos basado en su valor de clave primaria.
     * Si no se encuentra el modelo, se lanzará una excepción HTTP 404.
     * @param int $idgenero Idgenero
     * @return Generos el modelo cargado
     * @throws NotFoundHttpException si no se puede encontrar el modelo
     */
    protected function findModel($idgenero)
    {
        if (($model = Generos::findOne(['idgenero' => $idgenero])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('La página solicitada no existe.');
    }
}

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use webvimark\modules\UserManagement\UserManagementModule;
use webvimark\modules\UserManagement\models\rbacDB\Role;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="images/favicon.ico" type="image/icon">
    
    <?php $this->registerCsrfMetaTags() ?>
    

    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => Html::img('@web/images/logoCuadrado.jpg', ['alt' => Yii::$app->name, 'style' => 'max-height:40px;']),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-black fixed-top beatbunker-mobile', // Modificado a navbar-black
        ],
        ]);

    // Verificación del rol del usuario
    if (!Yii::$app->user->isGuest && Yii::$app->user->identity->username === 'superadmin') {
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav beatbunker-nav'],
            'items' => [
                ['label' => 'Canciones', 'url' => ['/canciones/index']],
                ['label' => 'Instrumentos', 'url' => ['/instrumentos/index']],
                ['label' => 'Generos', 'url' => ['/generos/index']],
                ['label' => 'Estudios', 'url' => ['/estudios/index']],
                ['label' => 'Herramientas', 'url' => ['/herramientas/index']],
                [
                    'label' => 'Gestión de permisos',
                    'items' => UserManagementModule::menuItems()
                ],
                [
                    'label' => 'Menú Sesión',
                    'items' => [
                        ['label' => 'Salir', 'url' => ['/user-management/auth/logout']],                        
                        ['label' => 'Cambiar contraseña', 'url' => ['/user-management/auth/change-own-password']],
                   
                    ],
                ],
            ],
        ]);
    } else {
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav beatbunker-nav'],
            'items' => [
                ['label' => 'Canciones', 'url' => ['/canciones/index']],
                ['label' => 'Instrumentos', 'url' => ['/instrumentos/index']],           
                ['label' => 'Estudios', 'url' => ['/estudios/index']],
                ['label' => 'Herramientas', 'url' => ['/herramientas/index']],
                [
                    'label' => 'Menú Sesión',
                    'items' => [
                        
                        ['label' => 'Salir', 'url' => ['/user-management/auth/logout']],
                        ['label' => 'Cambiar contraseña', 'url' => ['/user-management/auth/change-own-password']],
                      
                    ],
                ],
            ],
        ]);
    }

    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0 site-main">
    <div class="container">
        
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted">
    <div class="container">
        <p class="float-left">&copy; BeatBunker <?= date('Y') ?></p>
        <p class="float-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>