models/Instrumentos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "instrumentos".
 *
 * @property int $idinstrumento
 * @property string $tipo
 * @property string|null $marca
 * @property string|null $modelo
 * @property float|null $tamaño
 * @property string|null $material
 * @property string|null $url
 * @property int $idusuario
 *
 * @property User $usuario
 * @property Suenan[] $suenans
 * @property CancionInstrumento[] $cancionInstrumentos
 * @property Canciones[] $canciones
 */
class Instrumentos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'instrumentos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tipo'], 'required'],
            [['tamaño'], 'number'],
            [['tipo', 'material'], 'string', 'max' => 255],
            [['marca', 'modelo'], 'string', 'max' => 45],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'idinstrumento' => 'ID Instrumento',
            'tipo' => 'Tipo',
            'marca' => 'Marca',
            'modelo' => 'Modelo',
            'tamaño' => 'Tamaño',
            'material' => 'Material',
        ];
    }

    /**
     * Gets query for [[Suenans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSuenans()
    {
        return $this->hasMany(Suenan::class, ['idinstrumento' => 'idinstrumento']);
    }

    /**
     * Gets query for [[Canciones]].
     * 
     * @return \yii\db\ActiveQuery
     */
    public function getCanciones()
    {
        return $this->hasMany(Canciones::class, ['idcancion' => 'idcancion'])
                    ->viaTable('cancion_instrumento', ['idinstrumento' => 'idinstrumento']);
    }
    
    public function getCancionInstrumentos()
    {
        return $this->hasMany(CancionInstrumento::class, ['idinstrumento' => 'idinstrumento']);
    }
}

controllers/EstudiosController.php
<?php

namespace app\controllers;

use app\models\Estudios;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Yii;

/**
 * EstudiosController implements the CRUD actions for Estudios model.
 */
class EstudiosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return [
            'ghost-access'=> [
                'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
            ],
        ];
    }

    /**
     * Lists all Estudios models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Estudios::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Estudios model.
     * @param int $idestudio Idestudio
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($idestudio)
    {
        return $this->render('view', [
            'model' => $this->findModel($idestudio),
        ]);
    }

    /**
     * Creates a new Estudios model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
{
    $model = new Estudios();

    if (Yii::$app->request->isPost) {
        if ($model->load(Yii::$app->request->post())) {
            $idcancion = Yii::$app->request->post('idcancion');
            $model->idcancion = $idcancion;

            if ($model->save()) {
                return $this->redirect( ['herramientas/create', 'idestudio' => $model->idestudio ] );
            } else {
                Yii::error('Failed to save model: ' . print_r($model->errors, true));
            }
        } else {
            Yii::error('Failed to load data into model');
        }
    } else {
        Yii::info('Request is NOT POST');
        $model->loadDefaultValues();
    }

    return $this->render('create', [
        'model' => $model,
    ]);
}

    /**
     * Updates an existing Estudios model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $idestudio Idestudio
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($idestudio)
    {
        $model = $this->findModel($idestudio);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'idestudio' => $model->idestudio]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Estudios model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $idestudio Idestudio
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($idestudio)
    {
        $this->findModel($idestudio)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Estudios model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $idestudio Idestudio
     * @return Estudios the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($idestudio)
    {
        if (($model = Estudios::findOne(['idestudio' => $idestudio])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/InstrumentosController.php
<?php

namespace app\controllers;

use app\models\Instrumentos;
use app\models\CancionInstrumento;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use Yii;

/**
 * InstrumentosController implements the CRUD actions for Instrumentos model.
 */
class InstrumentosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return [
            'ghost-access'=> [
                'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
            ],
        ];
    }

    /**
     * Lists all Instrumentos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Instrumentos::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Instrumentos model.
     * @param int $idinstrumento Idinstrumento
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($idinstrumento)
    {
        return $this->render('view', [
            'model' => $this->findModel($idinstrumento),
        ]);
    }

    /**
     * Creates a new Instrumentos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Instrumentos();
        $instrumentos = [
            1 => 'Guitarra',
            2 => 'Bajo',
            3 => 'Bateria',
            4 => 'Caja',
            5 => 'HiHat',
            6 => 'Crash',
            7 => 'Ride',
            8 => 'Teclado'
        ];

        if (Yii::$app->request->isPost) {
            if ($model->load(Yii::$app->request->post())) {
                // Cambia índice seleccionado al nombre del instrumento
                if (isset($instrumentos[$model->tipo])) {
                    $model->tipo = $instrumentos[$model->tipo];
                }
                if ($model->save()) {
                    $idCancion = Yii::$app->request->post('idcancion');
                    if ($idCancion) {
                        $cancionInstrumento = new CancionInstrumento();
                        $cancionInstrumento->idcancion = $idCancion;
                        $cancionInstrumento->idinstrumento = $model->idinstrumento;

                        if ($cancionInstrumento->save()) {
                            Yii::info('Relación canción-instrumento guardada correctamente.');
                            return $this->redirect(['create', 'idcancion' => $idCancion]);
                        } else {
                            Yii::error('Error al guardar la relación canción-instrumento: ' . print_r($cancionInstrumento->errors, true));
                        }
                    } else {
                        return $this->redirect(['view']);
                    }
                } else {
                    Yii::error('Error al guardar el instrumento: ' . print_r($model->errors, true));
                }
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'instrumentos' => $instrumentos,
        ]);
    }

    /**
     * Updates an existing Instrumentos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $idinstrumento Idinstrumento
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($idinstrumento)
    {
        $model = $this->findModel($idinstrumento);
        $instrumentos = [
            1 => 'Guitarra', 
            2 => 'Bajo', 
            3 => 'Bateria', 
            4 => 'Caja', 
            5 => 'HiHat',
            6 => 'Crash', 
            7 => 'Ride', 
            8 => 'Teclado'
        ];

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'idinstrumento' => $model->idinstrumento]);
        }

        return $this->render('update', [
            'model' => $model,
            'instrumentos' => $instrumentos,
        ]);
    }

    /**
     * Deletes an existing Instrumentos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $idinstrumento Idinstrumento
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($idinstrumento)
    {
        $this->findModel($idinstrumento)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Instrumentos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $idinstrumento Idinstrumento
     * @return Instrumentos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($idinstrumento)
    {
        if (($model = Instrumentos::findOne(['idinstrumento' => $idinstrumento])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/instrumentos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\Instrumentos $model */
/** @var yii\widgets\ActiveForm $form */
/** @var array $instrumentos */

$request = Yii::$app->request;

$idcancion = $request->get('idcancion');
?>


<div class="instrumentos-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'tipo')->dropDownList($instrumentos, ['prompt' => 'Seleccione un tipo de instrumento']) ?>

    <?= $form->field($model, 'marca')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'modelo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tamaño')->textInput() ?>

    <?= $form->field($model, 'material')->textInput(['maxlength' => true]) ?>
    
    <?= Html::hiddenInput('idcancion', $idcancion) ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
        <?php if($idcancion) : ?>
            <?= Html::a('Siguiente', ['estudios/create', 'idcancion' => $idcancion], ['class' => 'btn btn-success']) ?>
        <?php endif; ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<!--//$form->field($model, 'tipo')->dropDownList($generos, ['prompt' => 'Seleccione un género'])-->

views/instrumentos/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Instrumentos $model */
/** @var array $instrumentos */

$this->title = 'Añadir Instrumento';
$this->params['breadcrumbs'][] = ['label' => 'Instrumentos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="instrumentos-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'instrumentos' => $instrumentos, // Pasando la variable instrumentos
    ]) ?>

</div>

views/instrumentos/index.php
<?php

use app\models\Instrumentos;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Instrumentos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="instrumentos-index">

    <h1><?= Html::encode($this->title) ?></h1>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'tipo',
            'marca',
            'modelo',
            'tamaño',
            //'material',
            //'url:url',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Instrumentos $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'idinstrumento' => $model->idinstrumento]);
                 },
                 'visibleButtons' => [
                    'view' => function ($model, $key, $index) {
                        return true; 
                    },
                    'update' => function ($model, $key, $index) {
                        return Yii::$app->user->identity->superadmin == 1;
                    },
                    'delete' => function ($model, $key, $index) {
                        return Yii::$app->user->identity->superadmin == 1;
                    },
                ],
                 
            ],
        ],
    ]); ?>


</div>

views/instrumentos/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Instrumentos $model */
/** @var array $instrumentos */

$this->title = 'Modificar Intrumento: ' . $model->tipo;
$this->params['breadcrumbs'][] = ['label' => 'Instrumentos', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Editar';
?>
<div class="instrumentos-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'instrumentos' => $instrumentos, // Pasando la variable instrumentos
    ]) ?>

</div>

views/instrumentos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Instrumentos $model */

$this->title = $model->idinstrumento;
$this->params['breadcrumbs'][] = ['label' => 'Instrumentos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="instrumentos-view">

    
    <p>
        <?php if( Yii::$app->user->identity->superadmin == 1 ) : ?>
            <?= Html::a('Editar', ['update', 'idinstrumento' => $model->idinstrumento], ['class' => 'btn btn-primary']) ?>
        <?php endif; ?>
        <?= Html::a('Terminar', ['index'], ['class' => 'btn btn-primary']) ?>
        <?php if( Yii::$app->user->identity->superadmin == 1 ) : ?>
            <?= Html::a('Eliminar', ['delete', 'idinstrumento' => $model->idinstrumento], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ]) ?>
        <?php endif; ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'idinstrumento',
            'tipo',
            'marca',
            'modelo',
            'tamaño',
            //'material',
            //'url:url',
        ],
    ]) ?>

</div>